---
- name: Install and configure Zabbix agent
  hosts: all !zabbix_servers 
  become: true
  vars:
    zabbix_server_net: "10.10.11.0/24"
    zabbix_agent_hostname: "{{ inventory_hostname }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Установка Zabbix agent
      apt:
        name: zabbix-agent
        state: present
      when: ansible_os_family == "Debian"

    - name: Конфигурация zabbix_agent
      template:
        src: zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: 0644

    - name: Проверка
      service:
        name: zabbix-agent
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Restart Zabbix agent
      service:
        name: zabbix-agent
        state: restarted